#version: '3'

#services:
#  app:
#    image: node:20
#    ports:
#      - 4321:4321
#    working_dir: /app
#    command: npm run dev -- --host 0.0.0.0
#    volumes:
#      - ./:/app

version: '3'
services:
  astropaper:
    build:
      context: .
    ports:
      - "4321:80"
    container_name: astropaper

